#!/bin/sh

function get_status {
    local consul_num=${1:-0};
    kubectl get pods -owide;
    kubectl exec --tty -i consul-${consul_num} -- consul members -detailed;
    kubectl exec --tty -i consul-${consul_num} -- consul operator raft -list-peers -stale=true;
    kubectl exec --tty -i consul-${consul_num} -- consul info;

    kubectl exec --tty -i consul-${consul_num} -- consul kv put test 1
}

get_status;
exit;
kubectl delete pods consul-1 consul-2 consul-3;
sleep 1;
get_status;

sleep 20;

get_status;

kubectl patch statefulset/consul -p '{"spec":{"replicas": 3}}'
sleep 5;

get_status;

addr=$(kubectl exec --tty -i consul-0 -- consul operator raft -list-peers | awk '/leader/ {print $2}');
